// src/components/AdminEdit/AdminEdit.jsx
import { useState } from "react";

function AdminEdit({ providerEdit, handleCancelClick }) {
  console.log("providerEdit", providerEdit);
  const provider = providerEdit[0] || {};

  const [name, setName] = useState(provider.name);
  const [availability, setAvailability] = useState(provider.availability);

  function handleChange(e) {
    const { name, value } = e.target;
    if (name === "name") {
      setName(value);
      console.log(name, value);
    } else if (name === "availability") {
      setAvailability(!availability);
    }
  }

  return (
    <>
      {/* Admin provider edit form */}
      <div className="vstack gap-5 px-0">
        <div className="list-group">
          <div className="list-group-item p-4">
            <div className="pe-4">
              <h3 className="fs-5 mb-4 fw-semibold">{name}</h3>
              <form action="" className="form">
                <div className="row">
                  <div className="col-md-8 mb-3">
                    <label htmlFor="name" className="form-label">
                      Name
                    </label>
                    <input
                      onChange={handleChange}
                      defaultValue={name}
                      id="name"
                      name="name"
                      type="text"
                      className="form-control w-full"
                    />
                  </div>
                  <div className="col-md-8 mb-3">
                    <div className="form-check">
                      <input
                        onChange={handleChange}
                        checked={availability}
                        id="availability"
                        name="availability"
                        type="checkbox"
                        className="form-check-input"
                      />
                      <label
                        htmlFor="availability"
                        className="form-check-label"
                      >
                        Has availability
                      </label>
                    </div>
                  </div>
                  <div className="col-12 mb-3">
                    <div className="mt-4">
                      <button
                        type="submit"
                        className="btn btn-secondary d-inline me-3"
                      >
                        Save Changes
                      </button>
                      <button
                        onClick={handleCancelClick}
                        className="btn btn-outline-secondary d-inline me-3"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default AdminEdit;

// app/src/components/admin/AdminEdit.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { Provider } from '@/types/provider'

const props = defineProps<{
  provider: Provider | null
}>()

const emit = defineEmits<{
  save: [payload: { id: string; name: string; availability: boolean }]
  cancel: []
}>()

const name = ref('')
const availability = ref(false)

const providerName = computed(() => name.value || props.provider?.name || '')

watch(
  () => props.provider,
  (provider) => {
    name.value = provider?.name ?? ''
    availability.value = provider?.availability ?? false
  },
  { immediate: true },
)

function handleSubmit() {
  if (!props.provider) return
  emit('save', {
    id: props.provider.id,
    name: name.value,
    availability: availability.value,
  })
}
</script>

<template>
  <div class="vstack gap-5 px-0">
    <div class="list-group">
      <div class="list-group-item p-4">
        <div class="pe-4">
          <h3 class="fs-5 mb-4 fw-semibold">{{ providerName }}</h3>
          <form class="form" @submit.prevent="handleSubmit">
            <div class="row">
              <div class="col-md-8 mb-3">
                <label for="name" class="form-label">Name</label>
                <input id="name" v-model="name" name="name" type="text" class="form-control w-full" />
              </div>
              <div class="col-md-8 mb-3">
                <div class="form-check">
                  <input id="availability" v-model="availability" name="availability" type="checkbox" class="form-check-input" />
                  <label for="availability" class="form-check-label">Has availability</label>
                </div>
              </div>
              <div class="col-12 mb-3">
                <div class="mt-4">
                  <button type="submit" class="btn btn-secondary d-inline me-3">Save Changes</button>
                  <button type="button" class="btn btn-outline-secondary d-inline me-3" @click="emit('cancel')">
                    Cancel
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>
